export const ADD_WIN_NUMBER_ARRAY = "ADD_WIN_NUMBER_ARRAY";
export const CLEAR_WIN_NUMBER_ARRAY = "CLEAR_WIN_NUMBER_ARRAY";
export const ADD_LOTTERY_NUMBER_ARRAY = "ADD_LOTTERY_NUMBER_ARRAY";
export const RESET_LOTTERY_NUMBER_ARRAY = "RESET_LOTTERY_NUMBER_ARRAY";
export const CLEAR_LOTTERY_NUMBER_ARRAY = "CLEAR_LOTTERY_NUMBER_ARRAY";